// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH9fnuVjyFwSgko69wY-GDz0R8wp3sZTs',
    appId: '1:882720384433:web:9334745ab4daac822dc990',
    messagingSenderId: '882720384433',
    projectId: 'flutterfire-ui-codelab-7905d',
    authDomain: 'flutterfire-ui-codelab-7905d.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-7905d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrRTAeodNT7KFmkPcAfAUq6Lml3SeN12I',
    appId: '1:882720384433:android:0024a51b868511742dc990',
    messagingSenderId: '882720384433',
    projectId: 'flutterfire-ui-codelab-7905d',
    storageBucket: 'flutterfire-ui-codelab-7905d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEHrNLbh3axrJ1GsGUVSQwKsvmkc7MeFo',
    appId: '1:882720384433:ios:d694b274150bfec52dc990',
    messagingSenderId: '882720384433',
    projectId: 'flutterfire-ui-codelab-7905d',
    storageBucket: 'flutterfire-ui-codelab-7905d.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEHrNLbh3axrJ1GsGUVSQwKsvmkc7MeFo',
    appId: '1:882720384433:ios:cc9bfed28d423dfa2dc990',
    messagingSenderId: '882720384433',
    projectId: 'flutterfire-ui-codelab-7905d',
    storageBucket: 'flutterfire-ui-codelab-7905d.appspot.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
